In [1]:
import numpy as np
from Code import utility as u
from Code import ray as r
from Code import material as m

### Single Interation Tests

In [2]:
air = m.Material(1.0,0,{'mean':100000})
glass = m.Material(1.5,70E-6,{'mean':2.5E-7})
ray = r.Ray(u.normalize([0,1,1]),  np.array([0,0,0]), 0.5 )
ray.k

array([0.        , 0.70710678, 0.70710678])

In [3]:
ray.TIRQ([0,0,1],mat)

True

In [4]:
#should undergo TIR - k with negative z value
ray.refract(np.array([0,0,1]),mat)

array([ 0.        ,  0.70710678, -0.70710678])

In [14]:
#should NOT undergo TIR
ray.refract(u.normalize([0,.1,1]),mat)

array([-0.        ,  0.97625611,  0.21661952])

In [13]:
print(u.normalize([0,0.1,1]))
u.Refract3D(1.5,1.0,u.normalize([0,0,1]),u.normalize([0,0.1,1]))

[0.         0.09950372 0.99503719]


array([-0.        ,  0.14925558,  0.98879865])

## Cumulative Parameter Check

In [15]:
np.conj(1j)

-1j

In [19]:
np.linalg.inv(np.identity(2))

array([[1., 0.],
       [0., 1.]])